<!DOCTYPE html>
<html lang="fr">
	<head>
	 
		<title>E_HABILITATION</title>
		<meta name="description" content="description">
		<meta name="author" content="E_HABILITATION">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?php 
		$_user=Zend_Auth::getInstance()->getIdentity();
		
		?>
		
		
		 
		<?php $this->headLink()->appendStylesheet($this->baseUrl()."/ressources/plugins/bootstrap/bootstrap.css")?>
		
		 <?php $this->headLink()->appendStylesheet($this->baseUrl()."/ressources/plugins/jquery-ui/jquery-ui.min.css")?>
		
		<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"-->
		 <?php //$this->headLink()->appendStylesheet($this->baseUrl()."/ressources/css/font-awesome.min.css")?>
		 
		<link href='http://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'>--
		<?php //$this->headLink()->appendStylesheet($this->baseUrl()."/ressources/css/righteous.css")?>
		
		 <?php $this->headLink()->appendStylesheet($this->baseUrl()."/ressources/plugins/fancybox/jquery.fancybox.css")?>
		 
		 <?php $this->headLink()->appendStylesheet($this->baseUrl()."/ressources/plugins/fullcalendar/fullcalendar.css")?>
	 
		 <?php $this->headLink()->appendStylesheet($this->baseUrl()."/ressources/plugins/xcharts/xcharts.min.css")?>
		
 
		<?php $this->headLink()->appendStylesheet($this->baseUrl()."/ressources/plugins/select2/select2.css")?>
		
		 <?php $this->headLink()->appendStylesheet($this->baseUrl()."/ressources/plugins/justified-gallery/justifiedGallery.css")?>
		 <?php $this->headLink()->appendStylesheet($this->baseUrl()."/ressources/css/style_v1.css")?>
		 
		<?php $this->headLink()->appendStylesheet($this->baseUrl()."/ressources/plugins/chartist/chartist.min.css")?>
		<?php  $this->headLink() ->appendStylesheet($this->baseUrl().'/ressources/plugins/treeview2/src/skin-win8/ui.fancytree.css');?>
			
 
		
		<?php echo $this->headLink();?>
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
				<script src="http://getbootstrap.com/docs-assets/js/html5shiv.js"></script>
				<script src="http://getbootstrap.com/docs-assets/js/respond.min.js"></script>
		<![endif]-->
		
		
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!--<script src="http://code.jquery.com/jquery.js"></script>-->
<script src=""></script>
<?php $this->headScript()->appendFile($this->baseUrl().'/ressources/plugins/jquery/jquery.min.js');?>
 
<?php $this->headScript()->appendFile($this->baseUrl().'/ressources/plugins/jquery-ui/jquery-ui.min.js');?>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<?php $this->headScript()->appendFile($this->baseUrl().'/ressources/plugins/bootstrap/bootstrap.min.js');?>
<?php $this->headScript()->appendFile($this->baseUrl().'/ressources/plugins/justified-gallery/jquery.justifiedGallery.min.js');?>
<?php $this->headScript()->appendFile($this->baseUrl().'/ressources/plugins/tinymce/tinymce.min.js');?>
<?php $this->headScript()->appendFile($this->baseUrl().'/ressources/plugins/tinymce/jquery.tinymce.min.js');?>
<?php $this->headScript()->appendFile($this->baseUrl().'/ressources/plugins/select2/select2.min.js');?>
<?php $this->headScript()->appendFile($this->baseUrl().'/ressources/plugins/jquery-ui-timepicker-addon/jquery-ui-timepicker-addon.min.js');?>

 <?php  $this->headScript()->appendFile($this->baseUrl().'/ressources/plugins/treeview2/src/jquery.fancytree.js','text/javascript');?>
<?php $this->headScript()->appendFile($this->baseUrl().'/ressources/plugins/jquery.form.js');?>
<!-- All functions for this theme + document.ready processing -->
<?php $this->headScript()->appendFile($this->baseUrl().'/ressources/js/devoops.js');?>
<?php echo $this->headScript();?>

	</head>
<body>
<!--Start Header-->
<div id="screensaver">
	<canvas id="canvas"></canvas>
	<i class="fa fa-lock" id="screen_unlock"></i>
</div>
<div id="modalbox">
	<div class="devoops-modal">
		<div class="devoops-modal-header">
			<div class="modal-header-name">
				<span>Basic table</span>
			</div>
			<div class="box-icons">
				<a class="close-link">
					<i class="fa fa-times"></i>
				</a>
			</div>
		</div>
		<div class="devoops-modal-inner">
		</div>
		<div class="devoops-modal-bottom">
		</div>
	</div>
</div>
<header class="navbar">
	<div class="container-fluid expanded-panel">
		<div class="row">
			<div id="logo" class="col-xs-12 col-sm-2">
				<a href="index_v1.html">  
				<img src="<?=$this->baseUrl()?>/ressources/img/esen.jpg" width="160" height="43" alt="logo esen"></a>
			</div>
			<div id="top-panel" class="col-xs-12 col-sm-10">
				<div class="row">
					<div class="col-xs-8 col-sm-4">
						<div id="search">
							<input type="text" placeholder="search"/>
							<i class="fa fa-search"></i>
						</div>
					</div>
					<div class="col-xs-4 col-sm-8 top-panel-right">
						
						<ul class="nav navbar-nav pull-right panel-menu">
							<li class="hidden-xs">
								<a href="index.html" class="modal-link">
									<i class="fa fa-bell"></i>
									<span class="badge">7</span>
								</a>
							</li>
							<li class="hidden-xs">
								<a class="ajax-link" href="ajax/calendar.html">
									<i class="fa fa-calendar"></i>
									<span class="badge">7</span>
								</a>
							</li>
							<li class="hidden-xs">
								<a href="ajax/page_messages.html" class="ajax-link">
									<i class="fa fa-envelope"></i>
									<span class="badge">7</span>
								</a>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle account" data-toggle="dropdown">
									<div class="avatar">
										<img src="<?=$this->baseUrl()?>/ressources/img/avatar.jpg" class="img-circle" alt="avatar" />
									</div>
									<i class="fa fa-angle-down pull-right"></i>
									<div class="user-mini pull-right">
										<span class="welcome">Bonjour,</span>
										<span><?=$_user->nomens?> <?=$_user->prenomens?></span>
									</div>
								</a>
								<ul class="dropdown-menu">
									<li>
										<a href="#">
											<i class="fa fa-user"></i>
											<span>Profile</span>
										</a>
									</li>
									<li>
										<a href="ajax/page_messages.html" class="ajax-link">
											<i class="fa fa-envelope"></i>
											<span>Messages</span>
										</a>
									</li> 
									<li>
										<a href="#">
											<i class="fa fa-cog"></i>
											<span>Settings</span>
										</a>
									</li>
									<li>
										<a href="<?=$this->url(array('action'=>'logout','module'=>'habilitation','controller'=>'gestauth'))?>">
											<i class="fa fa-power-off"></i>
											<span>Logout</span>
										</a>
									</li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
<!--End Header-->
<!--Start Container-->
<div id="main" class="container-fluid">
	<div class="row">
		<div id="sidebar-left" class="col-xs-2 col-sm-2">
		 	 
        <?php 
		  $this->navigation()->menu()->setUlClass("nav main-menu");
		  $string=  $this->navigation()->menu()->renderMenu(null,array('maxDepth'   =>  0));
		   if(is_string($string)) {
		  	$string = str_replace(array('{{', '}}', '||'), array('<','>', '"'), $string);
		  }
		  echo   (utf8_decode($string)  ) ;
		?> 
			 
		</div>
		<!--Start Content-->
		<div id="content" class="col-xs-12 col-sm-10">
			<div id="about">
				<div class="about-inner">
					<h4 class="page-header">Esen </h4>
					<p>Oussama Limam : oussama.limam@gmail.com</p>
				</div>
			</div>
			
			 
			<div id="ajax-content">
			  <!--Start Breadcrumb-->
				<div class="row">
					<div id="breadcrumb" class="col-xs-12">
						<a href="#" class="show-sidebar">
							<i class="fa fa-bars"></i>
						</a>
						
					<?php
					    echo $this->navigation() // <-- Update this!!
					              ->breadcrumbs()
					              ->setMinDepth(0)
					              ->setPartial('breadcrumb.phtml');
    				?>
					 
						 
						<div id="social" class="pull-right">
							<a href="#"><i class="fa fa-bar-chart-o"></i></a>
							<a href="#"><i class="fa fa-gears"></i></a>
							
							<a href="#"><i class="fa  fa-question-circle"></i></a>
							<a href="#"><i class="fa fa-youtube"></i></a>
							<a href="#"><i class="fa fa-power-off"></i></a>
						</div>
					</div>
				</div>
				<!--End Breadcrumb-->
				<div class="row">
				
				<?php $this->navigation()->menu()->setUlClass("nav nav-pills nav-justified");?> 
				<?php $submenu= $this->navigation()->menu()->renderMenu(null,array("minDepth"=>1,"maxDepth"=>0,"onlyActiveBranch"=>true,"renderParents"=>false)) ;
				 	if(is_string($submenu)) {
						$submenu = str_replace(array('{{', '}}', '||'), array('<','>', '"'), $submenu);
					}
				echo (utf8_decode($submenu)) ; 
				 
				?>
				
				<!-- Modal -->
				<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				  <div class="modal-dialog">
				    <div class="modal-content">
				      <div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
				      </div>
				      <div class="modal-body" id="modal-body">
				        
				      </div>
				      <div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				        <button type="button" class="btn btn-primary">Save changes</button>
				      </div>
				    </div>
				  </div>
				</div>
				<!-- END modale -->
				
				<!-- Contenue de la page -->
				<div class="col-md-12" id="contenu-page">
					<?php echo $this->layout()->content; ?>
				</div>
				<!-- Fin Contenue de la page -->
				</div>
				
			</div>
		</div>
		<!--End Content-->
	</div>
</div>
<!--End Container-->

</body>
</html>







