
<style>
.col-lg-3 {
  width: 44%;
}
.panel {font-size: 22px;}

.col-xs-3 {
  width: 58%;
}

</style>




<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><strong   font-size: 32px;>Détails de votre demande</strong></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>


 <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="">Ajouter Une demande</i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"></div>
                                    <div></div>
                                </div>
                            </div>
                        </div>
                       <a href="<?=$this->url(array("module"=>"default","action"=>"creer","controller"=>"Demande"))?>">
						    <div class="panel-footer">
                                <span class="pull-left">Voir détails</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
               <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="">Modifier votre profile</i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"></div>
                                    <div></div>
                                </div>
                            </div>
                        </div>
                       <a href="<?=$this->url(array("module"=>"default","action"=>"espace","controller"=>"etudiant"))?>">
						    <div class="panel-footer">
                                <span class="pull-left">Voir détails</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
               
               
				
            </div>