<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Sharepoint</title>
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <!-- Le styles -->
        <?php 
   		echo $this->headScript()->prependFile($this->baseUrl().'/resources/js/jqueryui/js/jquery-1.8.3.min.js','text/javascript')	;
   		echo $this->headScript()->prependFile($this->baseUrl().'/resources/jQueryFileUploadmaster/js/vendor/jquery.ui.widget.js','text/javascript');
   	?>
        <?php 
   		echo $this->headLink()->prependStylesheet($this->baseUrl().'/resources/css/basebootstrap/css/bootstrap/bootstrap.css');
   		echo $this->headLink()->prependStylesheet($this->baseUrl().'/resources/css/basebootstrap/css/bootstrap/bootstrap-responsive.css');
		echo $this->headLink()->prependStylesheet($this->baseUrl().'/resources/css/modules/inscription/theme.css');
   ?>
    
   <?php 
     echo $this->headScript()->appendFile($this->baseUrl().'/resources/css/basebootstrap/js/bootstrap/bootstrap.min.js'); 
 	
   ?>
   
     <!-- Bootstrap Core CSS -->
    <link href="../bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="../bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="../bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
         
    </head>

  <body>

    

  <p>
        					<?php echo $this->layout()->content; ?>
        				</p>
        				
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
   
  
    

      <?php 
     echo $this->headScript()->appendFile($this->baseUrl().'/bower_components/jquery/dist/jquery.min.js');
     echo $this->headScript()->appendFile($this->baseUrl().'/bower_components/metisMenu/dist/metisMenu.min.js');
     echo $this->headScript()->appendFile($this->baseUrl().'/bower_components/bootstrap/dist/js/bootstrap.min.js');
     echo $this->headScript()->appendFile($this->baseUrl().'/bower_components/bootstrap/dist/js/metisMenu.min.js');
     echo $this->headScript()->appendFile($this->baseUrl().'/bower_components/bootstrap/dist/js/sb-admin-2.js');
 	
   ?>
   
  

</body></html>