<?php
$this->headTitle('Reorientation Management');
?>
<?php
$tableEtudiant = new Application_Mytables_Etudiant();
$tableDemande = new Application_Mytables_Demande();
$tableEtablissement = new Application_Mytables_Etablissement();
$tableParcours = new Application_Mytables_Parcours();
?>

    <script type="text/javascript">

        function Clean()
        {





        }

        function toggleCheckboxes(source)
        {
            var checkboxes = document.getElementsByName('del_id[]');
            for (var i = 0; i < checkboxes.length; i++)
            {
                checkboxes[i].checked = source.checked;
            }
        }

        function updateFilters(paramName, paramValue)
        {
            var newQuery = [];
            var args = {};
            var query = location.search.indexOf('?') > -1 ? location.search.substring(1).split('&') : [];

            for (var pairIndex = 0; pairIndex < query.length; pairIndex++) {
                var param = query[pairIndex].split('=');
                args[param[0]] = param[1];
            }

            args[paramName] = paramValue;
            for (var key in args)
            {
                newQuery.push(key + '=' + encodeURIComponent(args[key]));
            }

            self.location.href = '?' + newQuery.join('&');
        }
    </script>

    <div class="page-header">
        <h1>Reorientation Management</h1>
    </div>

    <div class="pull-right">
        <a class="btn btn-info" href="<?php echo $this->url(array('module' => 'admin','controller' => 'reorientation', 'action' => 'index'), null, true); ?>"><i class=" icon-refresh icon-white"></i> Reset Filters</a>
        <a class="btn btn-success" href="<?php echo $this->url(array('module' => 'admin','controller' => 'reorientation', 'action' => 'create'), null, true); ?>"><i class="icon-plus icon-white"></i> Add New</a></div><br />

    <form class="form form-inline" method="get" action="<?php echo $this->url(array('module' => 'admin','controller' => 'reorientation', 'action' => 'index'), null, true); ?>">
        <div>
            <input class="input-medium search-query" placeholder="Keywords..." type="text" name="_kw" value="<?php echo htmlspecialchars($this->param_kw); ?>" />
            <?php echo $this->formSelect('_sm', $this->param_sm, array(), array (
                'all' => 'All',
                'etablissement_actuel' => 'Etablissement Actuel',
                'section_actuelle' => 'Section Actuelle',
                'etablissement_demande' => 'Etablissement Demande',
            )); ?>

            <button class="btn" type="submit"><i class="icon-search"></i> Search</button>
        </div>
    </form>

    <form method="post" action="<?php echo $this->url(array('module' => 'admin','controller' => 'reorientation', 'action' => 'delete'), null, true); ?>" onsubmit="return confirm('Delete selected rows?');">

    <table class="table table-bordered table-striped" id="datatableS">
    <tfoot>
    <tr>
        <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
        <th<?php if ('codedem' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
            Codedem
            <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
            <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
            <?php
            echo $this->formSelect('codedem', $this->paramcodedem, array('onchange' => 'updateFilters(\'codedem\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableDemande->fetchPairs());
            ?>
        </th>
        <th<?php if ('etat' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
            Etat
            <a href='<?php echo $this->url($_GET + array('_sf' => 'etat', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
            <a href='<?php echo $this->url($_GET + array('_sf' => 'etat', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
            <?php echo $this->formSelect('etat', $this->parametat, array('onchange' => 'updateFilters(\'etat\', this.options[this.selectedIndex].value)'), array (
                '' => '- - Change - -',
                'En Attente' => 'En Attente',
                'Refuser' => 'Refuser',
                'Accepter' => 'Accepter',
            )); ?></th>


        <th<?php if ('etablissement_actuel' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
            Etablissement Actuel
            <a href='<?php echo $this->url($_GET + array('_sf' => 'etablissement_actuel', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
            <a href='<?php echo $this->url($_GET + array('_sf' => 'etablissement_actuel', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
            <?php
            echo $this->formSelect('etablissement_actuel', $this->parametablissement_actuel, array('onchange' => 'updateFilters(\'etablissement_actuel\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableEtablissement->fetchPairs());
            ?>
        </th>

        <th<?php if ('resultat' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
            Resultat
            <a href='<?php echo $this->url($_GET + array('_sf' => 'resultat', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
            <a href='<?php echo $this->url($_GET + array('_sf' => 'resultat', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
            <?php echo $this->formSelect('resultat', $this->paramresultat, array('onchange' => 'updateFilters(\'resultat\', this.options[this.selectedIndex].value)'), array (
                        '' => '- - Change - -',
                        'admis' => 'admis',
                        'redoublant' => 'redoublant',
                    )); ?>
        </th>
        <th<?php if ('etablissement_demande' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
            Etablissement Demande
            <a href='<?php echo $this->url($_GET + array('_sf' => 'etablissement_demande', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
            <a href='<?php echo $this->url($_GET + array('_sf' => 'etablissement_demande', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
            <?php
            echo $this->formSelect('etablissement_demande', $this->parametablissement_demande, array('onchange' => 'updateFilters(\'etablissement_demande\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableEtablissement->fetchPairs());
            ?>
        </th>
        <th<?php if ('section_demande' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
            Section Demande
            <a href='<?php echo $this->url($_GET + array('_sf' => 'section_demande', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
            <a href='<?php echo $this->url($_GET + array('_sf' => 'section_demande', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
            <?php
            echo $this->formSelect('section_demande', $this->paramsection_demande, array('onchange' => 'updateFilters(\'section_demande\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableParcours->fetchPairs());
            ?>
        </th>

    </tr>
    </tfoot></table>

    <table class="table table-bordered table-striped" id="datatable">
            <thead>
            <tr>
                <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
                <th<?php if ('codedem' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                    Codedem
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                    <?php
                    //echo $this->formSelect('codedem', $this->paramcodedem, array('onchange' => 'updateFilters(\'codedem\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableDemande->fetchPairs());
                    ?>
                </th>

                <th<?php if ('etat' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                    Etat
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'etat', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'etat', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                   </th>

                <th<?php if ('cin' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                    Cin
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'cin', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'cin', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>

                </th>
                <th<?php if ('nom' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                    Nom
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'nom', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'nom', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>

                </th>
                <th<?php if ('prenom' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                    Prenom
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'prenom', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'prenom', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>

                </th>
                <th<?php if ('etablissement_actuel' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                    Etablissement Actuel
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'etablissement_actuel', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'etablissement_actuel', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                    <?php
                    //echo $this->formSelect('etablissement_actuel', $this->parametablissement_actuel, array('onchange' => 'updateFilters(\'etablissement_actuel\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableEtablissement->fetchPairs());
                    ?>
                </th>
                <th<?php if ('section_actuelle' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                    Section Actuelle
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'section_actuelle', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'section_actuelle', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>

                </th>
                <th<?php if ('resultat' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                    Resultat
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'resultat', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'resultat', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                    <?php /*echo $this->formSelect('resultat', $this->paramresultat, array('onchange' => 'updateFilters(\'resultat\', this.options[this.selectedIndex].value)'), array (
                        '' => '- - Change - -',
                        'admis' => 'admis',
                        'redoublant' => 'redoublant',
                    ));*/ ?>
                </th>
                <th<?php if ('etablissement_demande' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                    Etablissement Demande
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'etablissement_demande', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'etablissement_demande', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                    <?php
                    //echo $this->formSelect('etablissement_demande', $this->parametablissement_demande, array('onchange' => 'updateFilters(\'etablissement_demande\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableEtablissement->fetchPairs());
                    ?>
                </th>
                <th<?php if ('section_demande' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                    Section Demande
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'section_demande', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'section_demande', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                    <?php
                    //echo $this->formSelect('section_demande', $this->paramsection_demande, array('onchange' => 'updateFilters(\'section_demande\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableParcours->fetchPairs());
                    ?>
                </th>
                <th<?php if ('date_demande' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                    Date Demande
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'date_demande', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                    <a href='<?php echo $this->url($_GET + array('_sf' => 'date_demande', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>

                </th>
                <th>Actions</th>
            </tr>
            </thead>



            <tbody>
            <?php foreach ($this->paginator as $row): ?>
                <tr>
                    <td align="center"><input type="checkbox" name="del_id[]" value="<?php echo $row->codedem; ?>" /></td>
                    <td><?php     $linkedRow = $tableDemande->find($row->codedem)->current();
                        if ($linkedRow) {
                            echo htmlspecialchars($linkedRow->getZodekenAutoLabel());
                        } else {
                            echo htmlspecialchars($linkedRow->codedem), ' (unlinked)';
                        } ?></td>
                    <td><?php  echo htmlspecialchars($linkedRow->getEtat()); ?></td>
                    <td><?php  echo htmlspecialchars($linkedRow->CIN); ?></td>

                    <td><?php     $linkedRowEtudiant = $tableEtudiant->find($linkedRow->CIN)->current();
                        if ($linkedRowEtudiant) {
                            echo htmlspecialchars($linkedRowEtudiant->getNom());
                        }?></td>


                    <td><?php      if ($linkedRowEtudiant) {
                            echo htmlspecialchars($linkedRowEtudiant->getPrenom());
                        } ?></td>



                    <td><?php
                        echo $tableEtablissement->findbyidJoin($row->etablissement_actuel);
                       ?></td>
                    <td><?php echo htmlspecialchars($row->section_actuelle); ?></td>
                    <td><?php echo htmlspecialchars($row->resultat); ?></td>
                    <td><?php    // $linkedRow = $tableEtablissement->find($row->etablissement_demande)->current();
                        echo $tableEtablissement->findbyidJoin($row->etablissement_demande);?></td>
                    <td><?php     $linkedRow = $tableParcours->find($row->section_demande)->current();
                        $linkedRow = $tableParcours->lookforparcours(null,null,null,$row->section_demande);
                        $linkedRow=$linkedRow[0];
                       // print_r($linkedRow);
                        if ($linkedRow) {
                          echo  $linkedRow['code'].' - '.$linkedRow['ldiplome'].'- -'.$linkedRow['description'];//.''.$linkedRow['mention'].''.$linkedRow['diplome_specialite'];
                        } else {

                        } ?></td>
                    <td><?php echo htmlspecialchars($row->date_demande); ?></td>
                    <td align="center">
                        <a href="<?php echo $this->url(array('module' => 'admin','controller' => 'demande', 'action' => 'decision', 'id' => $row->codedem), null, true); ?>">Décision</a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table><br />
        <!--<button class="btn btn-danger" type="submit"><i class=" icon-trash icon-white"></i> Delete Selected Rows</button>-->

        <a class="btn btn-success" download="somedata.xls"  href="#" onclick=" return ExcellentExport.excel(this, 'datatable', 'Sheet Name Here');">Export to Excel</a>

    </form>

<?php echo $this->paginationControl($this->paginator,
    'Sliding',
    'pagination_control.phtml');